# Generated by Django 4.1.7 on 2023-04-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyurtma',
        ),
    ]
