# Generated by Django 4.1.7 on 2023-04-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='shahar',
            field=models.CharField(max_length=600),
        ),
    ]
